import * as React from "react"
import { Link } from "gatsby"
import { StaticImage } from "gatsby-plugin-image"

import Layout from "../components/layout"
import SEO from "../components/seo"

const IndexPage = () => (
  <Layout>
    <SEO title="Home" />
    <div className="mt-6"></div>
    <div className="grid md:grid-cols-12 mx-4">
      <div className="md:col-start-5 md:col-span-4 text-center">
        <StaticImage
          src="../images/me-about.jpeg"
          width={200}
          quality={95}
          formats={["AUTO", "WEBP", "AVIF"]}
          alt="Me - photo"
          style={{ marginBottom: `1.45rem`, borderRadius: "100%" }}
        />
      </div>
      <div className="md:col-start-5 md:col-span-4">
        <div className="border border-white col-start-3 col-end-10 p-4 rounded-xl mr-auto">
          <p className="leading-tight">
            Hi! My name is Pedro. I'm a Computer Science working mainly with web
            development. This is my personal webpage and portfolio. I'm
            currently located in São Paulo, Brazil.
          </p>
        </div>
      </div>
      <div className="md:col-start-2 md:col-span-10">
        <ul>
          <li>
            <div className="border border-white col-start-3 col-end-10 p-4 rounded-xl my-4 mr-auto">
              <h3 className="font-semibold text-lg mb-1 underline">
                Graduation 2012-2017
              </h3>
              <p className="leading-tight">
                Graduated in Computer Science from UEL (Universidade Estadual de
                Londrina).
              </p>
              <br />
              <p>
                My final thesis was on the field of Computer Security. The
                thesis's main idea consisted of applying the{" "}
                {
                  <Link
                    className="underline"
                    to="https://en.wikipedia.org/wiki/Modularity_(networks)"
                  >
                    modularity algorithm
                  </Link>
                }{" "}
                to a dataset of alerts generated by an{" "}
                {
                  <Link
                    className="underline"
                    to="https://en.wikipedia.org/wiki/Modularity_(networks)"
                  >
                    IDS (Intrusion Detection System)
                  </Link>
                }{" "}
                . This dataset was generated during a CTF contest (CTF is a
                Cyber Hacking Competition that stand for Capture the Flag) in
                2008, and the winner team gave an interview explaning how they
                proceeded to hack the computers located on a private network and
                capture the flag. To apply the modularity algorithm on the
                dataset we had to create a{" "}
                {
                  <Link
                    className="underline"
                    to="https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)"
                  >
                    Graph
                  </Link>
                }{" "}
                using the alerts's IP address Source and Destiny. The result
                from applying the modularity algorithm on this graph, and with
                the help of an algorithm for visualizing graphs, we obtained the
                following image:
              </p>
              <div className="text-center my-6">
                <StaticImage
                  src="../images/tcc-image.jpg"
                  width={400}
                  quality={95}
                  formats={["AUTO", "WEBP", "AVIF"]}
                  alt="Tcc image"
                  style={{ borderRadius: "10px" }}
                />
                <p className="text-sm italic">
                  Note 1.: I had to reduce the quality of the image because of
                  the file size. Because of that, one edge is missing connecting
                  the green vertice isolated and closest to the red vertices, to
                  the red vertice isolated and centered between the group of red
                  vertices and the group of red and purple vertices. This edge
                  is important because it identify the first computer
                  comprimised and the connection to the second one compromised.
                </p>
                <p className="text-sm italic">
                  Note 2.: Because this is a small and no-interactive image, I
                  had to remove the vertice's IP address from the the image. The
                  IP addresses are useful to identify each computer on the
                  network. And, also, to discovery the compromised computers
                  using the detailed interview given by the winner team of the
                  CTF contest.
                </p>
              </div>
              <p>
                Short description of the image: the vertices represent computers
                (we call them hosts for now on) and the edges the interactions
                among them. The colours are added by the algorithm for
                visualizing graphs and used to distinguish group of hosts with
                common interactions among them (these group are the result of
                applying the modularity algorithm to the graph). The vertices
                with high number of edges and isolated from the group of
                vertices are the hosts that were compromised or have experienced
                multiple attempts of attack.
              </p>
              <br />
              <p>
                Final, with the detailed interview given by the winner team of
                the CTF contest we could understand how the attacks and
                compromises were made, and prove our hypotheses from solely
                analyzing the graph image. From the image we were able to
                identify the hosts that were compromised and the ones under
                attack. A real-time and interactively application using this
                technique would be able to show, visually, the chronological
                order of attacks and compromised hosts.
              </p>
            </div>
          </li>
          <li>
            <div className="border border-white col-start-3 col-end-10 p-4 rounded-xl my-4 mr-auto">
              <h3 className="font-semibold text-lg mb-1 underline">
                GL Consultoria 2017-2021
              </h3>
              <p className="leading-tight">
                <ul className="list-disc ml-4">
                  <li>Help the company on the </li>
                </ul>
              </p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </Layout>
)

export default IndexPage
